### ISSUE TITLE
Handle the approver and administrator of the transaction

### ISSUE THREAD

**Issue by xpdlf1004** [CodeChain-io/codechain-indexer#17]

**Comment by majecty** [comment]
Since there are no explicit requirements, I will implement the simple version of the function now and cope with the future conditions later.

Finding transactions with the approver and administrator is to find all the asset types for which the specific address is in the approver or administrator and find all the transactions associated with that asset type.

The indexer already can find transactions with an asset type, so I'll implement the ability to find all AssetSchemes with a specific address of approver or administrator.

**Comment by majecty** [comment]
I don't remember correctly. It seems we don't need to fix this issue.
